#!/usr/bin/env python3
# Copyright 2026 CORSA.pro (https://www.corsa.pro)
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
"""Rebuild static/src/css/fontawesome_editor.css from the bundled Font Awesome.

Odoo 19's HTML editor lists Font Awesome icons, and its email conversion turns
them into images, by reading ``.fa-name::before {content: "..."}`` rules from
the page's style sheets. Font Awesome 6 sets its icons through a CSS variable
(``.fa-name {--fa: "..."}``) instead, so with this module installed the editor
listed no icon and emails kept none. The generated file gives every icon such
a rule, with the codepoint ``fa fa-name`` markup draws: the Font Awesome 4
names of ``v4-shims.css`` win over a Font Awesome 6 icon of the same name, as
they do on the page.

Run it after updating the Font Awesome files::

    python3 base_fontawesome/scripts/build_editor_css.py
"""

import pathlib
import re
import sys
from collections import defaultdict

MODULE = pathlib.Path(__file__).resolve().parent.parent
COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
RULE = re.compile(r"([^{}]+)\{([^{}]*)\}")
VARIABLE = re.compile(r'--fa:\s*"([^"]+)"')


def codepoints(css, selector):
    """Icon name -> codepoint escape, for the rules matching ``selector``."""
    result = {}
    css = COMMENT.sub("", css)
    for selectors, body in RULE.findall(css):
        value = VARIABLE.search(body)
        if not value:
            continue
        for part in selectors.split(","):
            name = re.fullmatch(selector, part.strip())
            if name:
                result.setdefault(name.group(1), value.group(1))
    return result


def build(lib):
    css = lib / "css"
    icons = codepoints((css / "all.css").read_text(), r"\.fa-([a-z0-9-]+)")
    # "fa fa-name" markup: the v4 rules are more specific and win.
    icons.update(
        codepoints((css / "v4-shims.css").read_text(), r"\.fa\.fa-([a-z0-9-]+)")
    )
    names_by_codepoint = defaultdict(list)
    for name, codepoint in icons.items():
        names_by_codepoint[codepoint].append(name)
    rules = sorted(
        (sorted(names), codepoint) for codepoint, names in names_by_codepoint.items()
    )
    lines = [
        "/* Generated by base_fontawesome/scripts/build_editor_css.py from",
        f"   {lib.name}: do not edit. Odoo's HTML editor and email conversion",
        "   read icons from ::before rules (see the script). */",
    ]
    # Formatted as prettier formats CSS, so that pre-commit leaves it as is.
    for names, codepoint in rules:
        lines.append(",\n".join(f".fa-{name}::before" for name in names) + " {")
        lines.append(f'    content: "{codepoint}";')
        lines.append("}")
    return "\n".join(lines) + "\n", len(icons), len(rules)


def main():
    (lib,) = sorted((MODULE / "static/lib").glob("fontawesome-*"))
    content, names, glyphs = build(lib)
    target = MODULE / "static/src/css/fontawesome_editor.css"
    target.write_text(content)
    sys.stdout.write(f"{target.name}: {glyphs} icons, {names} names\n")


if __name__ == "__main__":
    main()
